"""
Mathematical operators of the Immortal Jellyfish Algorithm.

Each operator is a pure function that takes positions and parameters and
returns updated positions (or fitness values), never modifying inputs in-place.
"""

from math import gamma, pi, sin
from typing import Callable, Tuple

import numpy as np


def levy_flight(beta: float, size: int) -> np.ndarray:
    """
    Generate Lévy-distributed steps via Mantegna's algorithm.

    Parameters
    ----------
    beta : float
        Stability index, typically in (1, 2).
    size : int
        Number of samples.
    """
    numerator = gamma(1.0 + beta) * sin(pi * beta / 2.0)
    denominator = gamma((1.0 + beta) / 2.0) * beta * (2.0 ** ((beta - 1.0) / 2.0))
    sigma_u = (numerator / denominator) ** (1.0 / beta)
    u = np.random.normal(0.0, sigma_u, size)
    v = np.random.normal(0.0, 1.0, size)
    return u / (np.abs(v) ** (1.0 / beta))


def apply_levy_exploration(
    position: np.ndarray,
    global_best: np.ndarray,
    lb: np.ndarray,
    ub: np.ndarray,
    beta: float = 1.5,
) -> np.ndarray:
    """
    Polyp-phase exploration: heavy-tailed random walk biased toward global best.
    """
    dim = len(position)
    step_scale = 0.01 * (ub - lb)
    step = step_scale * levy_flight(beta, dim) * (position - global_best)
    return np.clip(position + step, lb, ub)


def apply_lighthouse_attraction(
    position: np.ndarray,
    lighthouse: np.ndarray,
    intensity: float,
    alpha: float,
    lb: np.ndarray,
    ub: np.ndarray,
) -> np.ndarray:
    """
    Medusa-phase attraction toward an elite lighthouse position.
    """
    dim = len(position)
    dist = np.linalg.norm(position - lighthouse)
    noise = 0.01 * np.random.randn(dim) * dist
    delta = alpha * intensity * (lighthouse - position) + noise
    return np.clip(position + delta, lb, ub)


def apply_pulse_swimming(
    position: np.ndarray,
    tau: float,
    personal_phase: float,
    lb: np.ndarray,
    ub: np.ndarray,
    amplitude_0: float = 0.1,
    frequency: float = 0.5,
) -> np.ndarray:
    """
    Sinusoidal bell-contraction swimming with per-agent phase offset.
    """
    amplitude = amplitude_0 * (1.0 - tau) ** 2
    oscillation = amplitude * sin(2.0 * pi * frequency * tau + personal_phase)
    delta = oscillation * (ub - lb)
    return np.clip(position + delta, lb, ub)


def strobilate(
    position: np.ndarray,
    fitness: float,
    objective: Callable[[np.ndarray], float],
    n_ephyra: int,
    lb: np.ndarray,
    ub: np.ndarray,
    beta: float = 1.5,
) -> Tuple[np.ndarray, float]:
    """
    Strobilation operator: produce n_ephyra candidate offspring and keep the best.

    Each ephyra is generated by adding a Lévy-scaled Gaussian perturbation.
    """
    dim = len(position)
    scale = (ub - lb) / 6.0
    best_pos = position.copy()
    best_fit = fitness
    for _ in range(n_ephyra):
        levy = levy_flight(beta, dim)
        candidate = np.clip(position + np.random.randn(dim) * levy * scale, lb, ub)
        candidate_fit = objective(candidate)
        if candidate_fit < best_fit:
            best_pos = candidate.copy()
            best_fit = candidate_fit
    return best_pos, best_fit


def transdifferentiate(
    position: np.ndarray,
    fitness: float,
    objective: Callable[[np.ndarray], float],
    lb: np.ndarray,
    ub: np.ndarray,
) -> Tuple[np.ndarray, float]:
    """
    Opposition-based restart (transdifferentiation).

    Computes the mirror image of the current position across the search space.
    Accepts the opposite if better; otherwise reinitialises uniformly at random.
    """
    opposite = np.clip(lb + ub - position, lb, ub)
    opposite_fit = objective(opposite)
    if opposite_fit < fitness:
        return opposite, opposite_fit
    new_pos = lb + np.random.rand(len(position)) * (ub - lb)
    return new_pos, objective(new_pos)


def archive_bud(
    position: np.ndarray,
    fitness: float,
    archive_member: np.ndarray,
    objective: Callable[[np.ndarray], float],
    lb: np.ndarray,
    ub: np.ndarray,
    beta: float = 1.5,
) -> Tuple[np.ndarray, float]:
    """
    Archive-based sexual reproduction (budding).

    Generates an offspring by a Lévy-scaled recombination with an archive member.
    """
    dim = len(position)
    levy = levy_flight(beta, dim)
    offspring = np.clip(position + levy * (position - archive_member), lb, ub)
    offspring_fit = objective(offspring)
    if offspring_fit < fitness:
        return offspring, offspring_fit
    return position, fitness


def senescence_refine(
    position: np.ndarray,
    fitness: float,
    global_best: np.ndarray,
    objective: Callable[[np.ndarray], float],
    lb: np.ndarray,
    ub: np.ndarray,
    tau: float,
) -> Tuple[np.ndarray, float]:
    """
    Fine-grained local search during senescence phase.

    Applies a tight Gaussian perturbation around the global best, with a spread
    that shrinks quadratically as tau → 1.
    """
    dim = len(position)
    spread = (ub - lb) * 0.05 * (1.0 - tau) ** 2
    candidate = np.clip(global_best + spread * np.random.randn(dim), lb, ub)
    candidate_fit = objective(candidate)
    if candidate_fit < fitness:
        return candidate, candidate_fit
    return position, fitness


def compute_diversity(
    population: np.ndarray,
    lb: np.ndarray,
    ub: np.ndarray,
) -> float:
    """
    Normalised mean absolute deviation of the population across all dimensions.

    Returns a value in [0, 0.5]; values below 0.005 indicate stagnation.
    """
    spread = np.where(ub - lb == 0, 1.0, ub - lb)
    center = population.mean(axis=0)
    return float(np.mean(np.abs(population - center) / spread))


def crowding_distance(fitnesses: np.ndarray) -> np.ndarray:
    """
    Compute scalar crowding distances in objective space (1-D case).

    Used to maintain diversity inside the elite archive.
    """
    n = len(fitnesses)
    if n <= 2:
        return np.full(n, np.inf)
    order = np.argsort(fitnesses)
    distances = np.zeros(n)
    f_range = fitnesses[order[-1]] - fitnesses[order[0]]
    if f_range == 0:
        return distances
    distances[order[0]] = np.inf
    distances[order[-1]] = np.inf
    for k in range(1, n - 1):
        distances[order[k]] = (fitnesses[order[k + 1]] - fitnesses[order[k - 1]]) / f_range
    return distances
